Here I will be cleaning the EEOC1_Master_Stacked Data Set

In [1]:
import pandas as pd
import dtale
import numpy as np

In [2]:
raw_df = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC1_Master_Stacked.csv')

C:\Users\jfraz\AppData\Local\Temp\ipykernel_62720\1824601255.py:1: DtypeWarning: Columns (0: Region, 1: Division, 2: State, 3: County, 4: White_Total, 5: Hisp_Total, 6: NHOPIT10, 7: Male_Total, 8: Female_Total, 9: TOTAL1_2, 10: WHM10, 11: WHF10, 12: NHOPIT1, 13: NHOPIT2, 14: NHOPIT3, 15: NHOPIT4, 16: NHOPIT5, 17: NHOPIT6, 18: NHOPIT7, 19: NHOPIT8, 20: NHOPIT9, 21: NHOPIT1_2, 22: TOMRT1, 23: TOMRT2, 24: TOMRT3, 25: TOMRT4, 26: TOMRT5, 27: TOMRT6, 28: TOMRT7, 29: TOMRT8, 30: TOMRT9, 31: TOMRT1_2, 32: nhopiT10, 33: nhopiT1, 34: nhopiT2, 35: nhopiT3, 36: nhopiT4, 37: nhopiT5, 38: nhopiT6, 39: nhopiT7, 40: nhopiT8, 41: nhopiT9, 42: nhopiT1_2, 43: tomrT1, 44: tomrT2, 45: tomrT3, 46: tomrT4, 47: tomrT5, 48: tomrT6, 49: tomrT7, 50: tomrT8, 51: tomrT9, 52: tomrT1_2) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_df = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC1_Master_Stacked.csv')

In [ ]:
# Created a copy file so when I mess up, I don't have to keep loading the original dataframe"
df = raw_df.copy()

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 561371 entries, 0 to 561370
Columns: 297 entries, Nation to tomrT1_2
dtypes: float64(2), int64(3), object(7), str(285)
memory usage: 1.2+ GB

In [5]:
df.head()

,Nation,Region,Division,State,CBSA,County,NAICS2,NAICS2_Name,NAICS3,NAICS3_Name,...,tomrT1,tomrT2,tomrT3,tomrT4,tomrT5,tomrT6,tomrT7,tomrT8,tomrT9,tomrT1_2
0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",111.0,Crop Production,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",112.0,Animal Production and Aquaculture,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",113.0,Forestry and Logging,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
d = dtale.show(df)
d.open_browser()

In [7]:
#Moving the 'Year' column to the first position on the dataframe
move_columns = df.pop('Year')
df.insert(0, 'Year', move_columns)
df.head()

,Year,Nation,Region,Division,State,CBSA,County,NAICS2,NAICS2_Name,NAICS3,...,tomrT1,tomrT2,tomrT3,tomrT4,tomrT5,tomrT6,tomrT7,tomrT8,tomrT9,tomrT1_2
0,2014,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",111.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",113.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#quick check of how many rows where in some of the original data frames before being stacked
df2023 = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_1_Data\EEOC1_2023.csv')
df2023.info()

C:\Users\jfraz\AppData\Local\Temp\ipykernel_62720\903303456.py:2: DtypeWarning: Columns (0: Region, 1: Division, 2: State, 3: County) have mixed types. Specify dtype option on import or set low_memory=False.
  df2023 = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_1_Data\EEOC1_2023.csv')

<class 'pandas.DataFrame'>
RangeIndex: 105613 entries, 0 to 105612
Columns: 275 entries, Nation to TOMRF1_2
dtypes: float64(2), int64(2), str(271)
memory usage: 221.6 MB

In [9]:
df2014 = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_1_Data\EEOC1_2014.csv')
df2014.info()

<class 'pandas.DataFrame'>
RangeIndex: 43707 entries, 0 to 43706
Columns: 275 entries, Nation to TOMRF1_2
dtypes: float64(2), int64(4), object(2), str(267)
memory usage: 91.7+ MB

C:\Users\jfraz\AppData\Local\Temp\ipykernel_62720\1575267954.py:1: DtypeWarning: Columns (0: Region, 1: Division, 2: State, 3: County, 4: WHT10, 5: TOTAL1_2) have mixed types. Specify dtype option on import or set low_memory=False.
  df2014 = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_1_Data\EEOC1_2014.csv')

In [10]:
df2019 = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_1_Data\EEOC1_2019.csv')
df2019.info()

<class 'pandas.DataFrame'>
RangeIndex: 44332 entries, 0 to 44331
Columns: 275 entries, Nation to TOMRF1_2
dtypes: float64(2), int64(2), object(5), str(266)
memory usage: 93.0+ MB

C:\Users\jfraz\AppData\Local\Temp\ipykernel_62720\2393504089.py:1: DtypeWarning: Columns (0: Region, 1: Division, 2: State, 3: County, 4: WHT10, 5: HISPT10, 6: MT10, 7: FT10, 8: TOTAL1_2) have mixed types. Specify dtype option on import or set low_memory=False.
  df2019 = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_1_Data\EEOC1_2019.csv')

In [11]:
df.describe()

,Year,NAICS2,NAICS3,Establishments,TOTAL10
count,561371.000000,525862.000000,287405.000000,5.613710e+05,5.613710e+05
mean,2019.366909,47.904688,478.318853,1.608241e+02,1.782720e+04
std,3.039839,14.540069,139.842270,3.984681e+03,3.222429e+05
min,2014.000000,11.000000,111.000000,3.000000e+00,3.000000e+00
25%,2017.000000,33.000000,336.000000,5.000000e+00,4.140000e+02
50%,2020.000000,48.000000,458.000000,1.200000e+01,1.173000e+03
75%,2022.000000,56.000000,561.000000,3.600000e+01,4.252000e+03
max,2023.000000,92.000000,928.000000,1.585519e+06,7.784510e+07

In [12]:
df.value_counts()

Series([], Name: count, dtype: int64)

In [13]:
df.describe(include='all')

,Year,Nation,Region,Division,State,CBSA,County,NAICS2,NAICS2_Name,NAICS3,...,tomrT1,tomrT2,tomrT3,tomrT4,tomrT5,tomrT6,tomrT7,tomrT8,tomrT9,tomrT1_2
count,561371.000000,561371,533059,528575,519315,472803,301101,525862.000000,525862,287405.000000,...,341378,341378,341378,341378,341378,341378,341378,341378,341378,341378
unique,NaN,1,4,9,51,932,1835,NaN,20,NaN,...,695,3392,1709,2791,2775,1376,2101,2250,3190,2157
top,NaN,United States,South,South Atlantic,Texas,"New York-Newark-Jersey City, NY-NJ-PA",Washington,NaN,Manufacturing,NaN,...,*,*,*,*,*,*,*,*,*,*
freq,NaN,561371,210607,103015,34481,11529,3617,NaN,98526,NaN,...,326039,250547,285146,258543,248752,291415,255233,263593,286274,254857
mean,2019.366909,NaN,NaN,NaN,NaN,NaN,NaN,47.904688,NaN,478.318853,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,3.039839,NaN,NaN,NaN,NaN,NaN,NaN,14.540069,NaN,139.842270,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2014.000000,NaN,NaN,NaN,NaN,NaN,NaN,11.000000,NaN,111.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2017.000000,NaN,NaN,NaN,NaN,NaN,NaN,33.000000,NaN,336.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2020.000000,NaN,NaN,NaN,NaN,NaN,NaN,48.000000,NaN,458.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2022.000000,NaN,NaN,NaN,NaN,NaN,NaN,56.000000,NaN,561.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2023.000000,NaN,NaN,NaN,NaN,NaN,NaN,92.000000,NaN,928.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#searching for duplicates
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
561366    False
561367    False
561368    False
561369    False
561370    False
Length: 561371, dtype: bool

In [15]:
#another check for duplicates
duplicates_only = df[df.duplicated()]
print(duplicates_only)

Empty DataFrame
Columns: [Year, Nation, Region, Division, State, CBSA, County, NAICS2, NAICS2_Name, NAICS3, NAICS3_Name, Establishments, TOTAL10, White_Total, Black_Total, Hisp_Total, Asian_Total, Amer_Ind_Total, NHOPIT10, Multi_Race_Total, Male_Total, Female_Total, Senior_Managers, Professionals, Technicians, Sales_Workers, Clericals, Craft, Operatives, Labors, Mid_Managers, TOTAL1_2, WHM10, BLKM10, HISPM10, ASIANM10, AIANM10, P_Isld_Total, TOMRM10, WHF10, BLKF10, HISPF10, ASIANF10, AIANF10, NHOPIF10, TOMRF10, WHT1, WHT2, WHT3, WHT4, WHT5, WHT6, WHT7, WHT8, WHT9, WHT1_2, BLKT1, BLKT2, BLKT3, BLKT4, BLKT5, BLKT6, BLKT7, BLKT8, BLKT9, BLKT1_2, HISPT1, HISPT2, HISPT3, HISPT4, HISPT5, HISPT6, HISPT7, HISPT8, HISPT9, HISPT1_2, ASIANT1, ASIANT2, ASIANT3, ASIANT4, ASIANT5, ASIANT6, ASIANT7, ASIANT8, ASIANT9, ASIANT1_2, AIANT1, AIANT2, AIANT3, AIANT4, AIANT5, AIANT6, AIANT7, AIANT8, AIANT9, AIANT1_2, NHOPIT1, NHOPIT2, NHOPIT3, NHOPIT4, ...]
Index: []

[0 rows x 297 columns]

In [16]:
df.isnull()

,Year,Nation,Region,Division,State,CBSA,County,NAICS2,NAICS2_Name,NAICS3,...,tomrT1,tomrT2,tomrT3,tomrT4,tomrT5,tomrT6,tomrT7,tomrT8,tomrT9,tomrT1_2
0,False,False,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,False,False,True,True,True,True,True,False,False,True,...,True,True,True,True,True,True,True,True,True,True
2,False,False,True,True,True,True,True,False,False,False,...,True,True,True,True,True,True,True,True,True,True
3,False,False,True,True,True,True,True,False,False,False,...,True,True,True,True,True,True,True,True,True,True
4,False,False,True,True,True,True,True,False,False,False,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561366,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
561367,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
561368,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
561369,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
561370,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [17]:
df.head()

,Year,Nation,Region,Division,State,CBSA,County,NAICS2,NAICS2_Name,NAICS3,...,tomrT1,tomrT2,tomrT3,tomrT4,tomrT5,tomrT6,tomrT7,tomrT8,tomrT9,tomrT1_2
0,2014,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",111.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",113.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
#Replaceing the '*' values with NaN in the columns I want to make numeric. 
df.replace('*', np.nan, inplace=True)
d = dtale.show(df)
d.open_browser()

In [26]:
df.iloc[:, 11]

0         260632
1           1268
2            587
3            349
4             30
           ...
561366       100
561367        24
561368        62
561369        24
561370         7
Name: Establishments, Length: 561371, dtype: int64

In [28]:
#I need to change all of my columns after 'Establishments' to numeric
#df.iloc[:, 11:] = pd.to_numeric(df.iloc[:, 11:], errors= 'coerce')
#df.dtypes
#df.info()

In [29]:
#The above cell didn't work. After researching, I'm trying this code instead
df.iloc[:, 11:] = df.iloc[:, 11:].apply(pd.to_numeric, errors='coerce')
df.dtypes
df.info()

TypeError: Invalid value '0         7408929.0
1           15875.0
2            3682.0
3            9389.0
4             132.0
            ...
561366         51.0
561367         36.0
561368         34.0
561369          4.0
561370          NaN
Name: Black_Total, Length: 561371, dtype: float64' for dtype 'str'

In [30]:
# 1. Grab the first 11 columns (leave them exactly as they are)
left_side = df.iloc[:, :11]

# 2. Grab column 11 onwards and convert them to numbers
right_side = df.iloc[:, 11:].apply(pd.to_numeric, errors='coerce')

# 3. Glue them back together side-by-side (axis=1) into a new dataframe
df = pd.concat([left_side, right_side], axis=1)

df.dtypes
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 561371 entries, 0 to 561370
Columns: 297 entries, Year to tomrT1_2
dtypes: float64(286), int64(3), str(8)
memory usage: 1.2 GB

In [31]:
d = dtale.show(df)
d.open_browser()
df.head()

,Year,Nation,Region,Division,State,CBSA,County,NAICS2,NAICS2_Name,NAICS3,...,tomrT1,tomrT2,tomrT3,tomrT4,tomrT5,tomrT6,tomrT7,tomrT8,tomrT9,tomrT1_2
0,2014,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",111.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",113.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Change all floats to int