After using my auto cleaning script on EEOC1_2022 I was surpised to see that the Dataframe is signifcantly smaller than EEOC1_2023. Here I am opening both the original and cleaned versions of EEOC_2022 to see what went wrong.

In [4]:
import pandas as pd

In [5]:
df_org = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_1_Data\EEOC1_2022.csv')
df_cln = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_Cleaned_Data\EEOC1_2022_Cleaned.csv')

C:\Users\jfraz\AppData\Local\Temp\ipykernel_14836\94692994.py:1: DtypeWarning: Columns (0: Region, 1: Division, 2: State, 3: County) have mixed types. Specify dtype option on import or set low_memory=False.
  df_org = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_1_Data\EEOC1_2022.csv')

In [6]:
df_org.head()

,Nation,Region,Division,State,CBSA,County,NAICS2,NAICS2_Name,NAICS3,NAICS3_Name,...,AIANM1_2,NHOPIM1_2,TOMRM1_2,WHF1_2,BLKF1_2,HISPF1_2,ASIANF1_2,AIANF1_2,NHOPIF1_2,TOMRF1_2
0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18369,19879,88770,2289452,358405,388702,253117,15451,15889,82420
1,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",NaN,NaN,...,120,47,175,5359,555,1970,214,61,24,138
2,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",111.0,Crop Production,...,*,*,91,*,106,*,98,*,*,69
3,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",112.0,Animal Production and Aquaculture,...,50,7,51,2462,392,468,82,22,7,51
4,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",113.0,Forestry and Logging,...,*,*,*,103,6,5,*,*,*,*

In [7]:
df_org_excel = pd.read_excel(r'c:\Users\jfraz\Downloads\EEO1 2022 PUF.xlsx')

In [8]:
df_org_excel.head()

,Nation,Region,Division,State,CBSA,County,NAICS2,NAICS2_Name,NAICS3,NAICS3_Name,...,AIANM1_2,NHOPIM1_2,TOMRM1_2,WHF1_2,BLKF1_2,HISPF1_2,ASIANF1_2,AIANF1_2,NHOPIF1_2,TOMRF1_2
0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18369,19879,88770,2289452,358405,388702,253117,15451,15889,82420
1,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",NaN,NaN,...,120,47,175,5359,555,1970,214,61,24,138
2,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",111.0,Crop Production,...,*,*,91,*,106,*,98,*,*,69
3,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",112.0,Animal Production and Aquaculture,...,50,7,51,2462,392,468,82,22,7,51
4,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",113.0,Forestry and Logging,...,*,*,*,103,6,5,*,*,*,*

In [9]:
df2023 = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_Cleaned_Data\EEOC1_2023_Cleaned.csv')
df2023.head()

,Year,State,County,NAICS2_Name,Male_Total,Female_Total,White_Total,Black_Total,Hisp_Total,Asian_Total,...,Multi_Race_Total,Senior_Managers,Professionals,Technicians,Sales_Workers,Clericals,Craft,Operatives,Labors,Mid_Managers
0,2023,NaN,NaN,NaN,39671364.0,38173733.0,42741322.0,11986834.0,14457050.0,5476881.0,...,2233847.0,1228770.0,17053752.0,4221921.0,9531002.0,8148679.0,3865601.0,7094110.0,6105353.0,12453155.0
1,2023,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",270931.0,135100.0,113103.0,30723.0,246872.0,6300.0,...,5456.0,5505.0,18931.0,14307.0,10298.0,17116.0,16154.0,60072.0,225197.0,8774.0
2,2023,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",108316.0,54489.0,40388.0,5647.0,111664.0,2236.0,...,1721.0,2378.0,6615.0,4516.0,7510.0,7421.0,4441.0,18106.0,94367.0,5273.0
3,2023,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",72318.0,39664.0,45576.0,21697.0,39627.0,2333.0,...,1302.0,1628.0,7431.0,6977.0,618.0,4363.0,6279.0,28320.0,44509.0,1367.0
4,2023,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",4167.0,940.0,3212.0,302.0,1439.0,34.0,...,48.0,118.0,699.0,92.0,81.0,401.0,280.0,1029.0,1793.0,40.0