Exploratory Data Analysis of EEOC1_Cleaned_Master.csv

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import os

In [4]:
df = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC1_Cleaned_Master\EEOC1_Master.csv')

In [5]:
df.head()

,Year,State,County,NAICS2_Name,Male_Total,Female_Total,White_Total,Black_Total,Hisp_Total,Asian_Total,...,Multi_Race_Total,Senior_Managers,Professionals,Technicians,Sales_Workers,Clericals,Craft,Operatives,Labors,Mid_Managers
0,2014,NaN,NaN,NaN,26728926.0,24422889.0,32348361.0,7408929.0,7066158.0,3068313.0,...,761483.0,833367.0,10534689.0,2870353.0,5681336.0,6533111.0,2950753.0,5337312.0,3777568.0,7867285.0
1,2014,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",187857.0,90345.0,86127.0,15875.0,165020.0,7013.0,...,1651.0,4044.0,13505.0,5874.0,7045.0,12631.0,12195.0,38015.0,159938.0,5716.0
2,2014,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",90891.0,43864.0,30544.0,3682.0,95595.0,3067.0,...,679.0,1854.0,7206.0,2037.0,4055.0,5378.0,4361.0,13319.0,85464.0,2455.0
3,2014,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",45938.0,22085.0,32517.0,9389.0,22823.0,2142.0,...,382.0,1055.0,2347.0,2230.0,724.0,3050.0,4449.0,12764.0,33742.0,1557.0
4,2014,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",2497.0,734.0,2650.0,132.0,305.0,54.0,...,26.0,84.0,786.0,116.0,45.0,275.0,499.0,624.0,348.0,80.0

In my previous data cleaning, I overlooked that the first row of my data set for each new year, shows an aggregated total for each value. I need to remove that aggregated total value.

In [6]:
#find the rows that are the first index for each year. These rows should contain the aggregated values in the columns.
#There should be 1 row for each year, totaling 10 rows
first_index_yr = df.groupby('Year').apply(lambda x: x.index[0])
first_index_yr.head(11)

Year
2014         0
2015     43707
2016     87886
2017    132346
2018    176074
2019    219993
2020    264325
2021    307140
2022    352283
2023    455758
dtype: int64

In [7]:
#Double checking to see if these are the correct rows
df.iloc[[0, 43707, 87886, 132346, 176074, 219993, 264325, 307140, 352283, 455758]]

,Year,State,County,NAICS2_Name,Male_Total,Female_Total,White_Total,Black_Total,Hisp_Total,Asian_Total,...,Multi_Race_Total,Senior_Managers,Professionals,Technicians,Sales_Workers,Clericals,Craft,Operatives,Labors,Mid_Managers
0,2014,NaN,NaN,NaN,26728926.0,24422889.0,32348361.0,7408929.0,7066158.0,3068313.0,...,761483.0,833367.0,10534689.0,2870353.0,5681336.0,6533111.0,2950753.0,5337312.0,3777568.0,7867285.0
43707,2015,NaN,NaN,NaN,27230059.0,24984168.0,32518080.0,7727631.0,7367573.0,3216149.0,...,865114.0,849503.0,10886751.0,2874230.0,5727042.0,6655739.0,2954660.0,5375033.0,3940681.0,8044564.0
87886,2016,NaN,NaN,NaN,28022940.0,25931674.0,33117054.0,8102655.0,7798683.0,3412700.0,...,976433.0,882506.0,11366236.0,2954159.0,5816155.0,6879142.0,2941205.0,5488431.0,4119461.0,8426896.0
132346,2017,NaN,NaN,NaN,28249468.0,26165885.0,32800729.0,8273600.0,8108979.0,3579101.0,...,1098185.0,870957.0,11703073.0,2901806.0,5785123.0,6803892.0,2913816.0,5596019.0,4421879.0,8264687.0
176074,2018,NaN,NaN,NaN,29049062.0,27024712.0,33283242.0,8543614.0,8642041.0,3792008.0,...,1232110.0,904227.0,12275798.0,3014359.0,5694610.0,6892696.0,3029306.0,5791371.0,4453077.0,8651560.0
219993,2019,NaN,NaN,NaN,29601281.0,27483919.0,33366115.0,8775729.0,9035649.0,3979895.0,...,1320545.0,917675.0,12808816.0,3028265.0,5859521.0,6507742.0,3044063.0,5969529.0,4823380.0,8605521.0
264325,2020,NaN,NaN,NaN,28335967.0,26138201.0,31737563.0,8249390.0,8730189.0,3911907.0,...,1273889.0,894104.0,12635135.0,2883647.0,5906622.0,6106461.0,2790733.0,5637314.0,5061595.0,7190176.0
307140,2021,NaN,NaN,NaN,30295627.0,28150807.0,33291865.0,8945931.0,9775047.0,4328675.0,...,1480912.0,967630.0,13686549.0,3023822.0,6389126.0,6460020.0,2933011.0,5880546.0,5264991.0,7976266.0
352283,2022,NaN,NaN,NaN,38794034.0,37048191.0,42409164.0,11647147.0,13499428.0,5248156.0,...,2110502.0,1168977.0,16496984.0,4049643.0,9471929.0,8166479.0,3731758.0,7075438.0,6030203.0,11728388.0
455758,2023,NaN,NaN,NaN,39671364.0,38173733.0,42741322.0,11986834.0,14457050.0,5476881.0,...,2233847.0,1228770.0,17053752.0,4221921.0,9531002.0,8148679.0,3865601.0,7094110.0,6105353.0,12453155.0

In [8]:
#Dropping those Specific aggregated rows
droped_ag_rows = df.drop(index=first_index_yr)

In [9]:
#testing to see if those aggrgated values were dropped from the dataset
droped_ag_rows.head()

,Year,State,County,NAICS2_Name,Male_Total,Female_Total,White_Total,Black_Total,Hisp_Total,Asian_Total,...,Multi_Race_Total,Senior_Managers,Professionals,Technicians,Sales_Workers,Clericals,Craft,Operatives,Labors,Mid_Managers
1,2014,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",187857.0,90345.0,86127.0,15875.0,165020.0,7013.0,...,1651.0,4044.0,13505.0,5874.0,7045.0,12631.0,12195.0,38015.0,159938.0,5716.0
2,2014,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",90891.0,43864.0,30544.0,3682.0,95595.0,3067.0,...,679.0,1854.0,7206.0,2037.0,4055.0,5378.0,4361.0,13319.0,85464.0,2455.0
3,2014,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",45938.0,22085.0,32517.0,9389.0,22823.0,2142.0,...,382.0,1055.0,2347.0,2230.0,724.0,3050.0,4449.0,12764.0,33742.0,1557.0
4,2014,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",2497.0,734.0,2650.0,132.0,305.0,54.0,...,26.0,84.0,786.0,116.0,45.0,275.0,499.0,624.0,348.0,80.0
5,2014,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",4631.0,1721.0,2387.0,1295.0,1727.0,577.0,...,122.0,103.0,200.0,46.0,302.0,394.0,310.0,1534.0,2853.0,115.0

In [19]:
#Ensure that the totals for the columns in the new dataframes equal the aggregated columns that were dropped
droped_ag_rows.groupby("Year")["Male_Total"].sum()

Year
2014    418903059.0
2015    427983216.0
2016    440648485.0
2017    442116510.0
2018    454592786.0
2019    465594232.0
2020    442442564.0
2021    476090469.0
2022    628944053.0
2023    644582430.0
Name: Male_Total, dtype: float64

The numbers above are higher than they should be! Compare those to the numbers below, which represent what the dropped aggregated values were originally in the data set. The issue is probably due to variables like State, Country, and NAICS2_Name, having null values that end up double counting the vaules that represent people.

In [21]:
#The total for Male_Total by year, in the original DataFrame for comparison purposes
df.iloc[[0, 43707, 87886, 132346, 176074, 219993, 264325, 307140, 352283, 455758]]["Male_Total"]

0         26728926.0
43707     27230059.0
87886     28022940.0
132346    28249468.0
176074    29049062.0
219993    29601281.0
264325    28335967.0
307140    30295627.0
352283    38794034.0
455758    39671364.0
Name: Male_Total, dtype: float64