Version 3.0 now adds percentage, varibales to each dataframe, to use instead of totals when cunducting historical analysis
This version 2 of EEOC1_Cleaning_Master_Stacked. Here I will be cleaning the EEOC1_Master_Stacked Data Set. 
BUT THIS TIME, I am also removing the Data that was causing double counting of values in newly created dataset.
Baselines will no longer overlap for Region, Division, CBSAs, etc.

In [1]:
import pandas as pd
import dtale
import numpy as np

In [2]:
raw_df = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC1_Master_Stacked.csv')

C:\Users\jfraz\AppData\Local\Temp\ipykernel_114424\1824601255.py:1: DtypeWarning: Columns (0: REGION, 1: DIVISION, 2: STATE, 3: COUNTY, 4: WHT10, 5: HISPT10, 6: MALE_TOTAL, 7: FEMALE_TOTAL, 8: TOTAL1_2, 9: WHM10, 10: WHF10) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_df = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC1_Master_Stacked.csv')

In [3]:
# Created a copy file so when I mess up, I don't have to keep loading the original dataframe"
df = raw_df.copy()

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 561371 entries, 0 to 561370
Columns: 276 entries, NATION to YEAR
dtypes: float64(2), int64(3), object(7), str(264)
memory usage: 1.2+ GB

In [5]:
df.head()

,NATION,REGION,DIVISION,STATE,CBSA,COUNTY,NAICS2,NAICS2_NAME,NAICS3,NAICS3_NAME,...,NHOPIM1_2,TOMRM1_2,WHF1_2,BLKF1_2,HISPF1_2,ASIANF1_2,AIANF1_2,NHOPIF1_2,TOMRF1_2,YEAR
0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7118,25224,1406699,170431,135342,110903,6999,5657,20823,2014
1,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",NaN,NaN,...,24,50,3327,175,743,142,27,13,37,2014
2,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",111.0,Crop Production,...,*,25,*,*,*,98,*,*,19,2014
3,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",112.0,Animal Production and Aquaculture,...,*,7,*,92,104,17,9,*,7,2014
4,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",113.0,Forestry and Logging,...,*,*,*,5,*,*,*,*,*,2014

In [6]:
#d = dtale.show(df)
#d.open_browser()

In [7]:
#Moving the 'Year' column to the first position on the dataframe
move_columns = df.pop('YEAR')
df.insert(0, 'YEAR', move_columns)
df.head()

,YEAR,NATION,REGION,DIVISION,STATE,CBSA,COUNTY,NAICS2,NAICS2_NAME,NAICS3,...,AIANM1_2,NHOPIM1_2,TOMRM1_2,WHF1_2,BLKF1_2,HISPF1_2,ASIANF1_2,AIANF1_2,NHOPIF1_2,TOMRF1_2
0,2014,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10881,7118,25224,1406699,170431,135342,110903,6999,5657,20823
1,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",NaN,...,85,24,50,3327,175,743,142,27,13,37
2,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",111.0,...,*,*,25,*,*,*,98,*,*,19
3,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",112.0,...,39,*,7,*,92,104,17,9,*,7
4,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",113.0,...,*,*,*,*,5,*,*,*,*,*

In [8]:
#Replaceing the '*' values with NaN in the columns I want to make numeric. 
df.replace('*', np.nan, inplace=True)
#d = dtale.show(df)
#d.open_browser()

,YEAR,NATION,REGION,DIVISION,STATE,CBSA,COUNTY,NAICS2,NAICS2_NAME,NAICS3,...,AIANM1_2,NHOPIM1_2,TOMRM1_2,WHF1_2,BLKF1_2,HISPF1_2,ASIANF1_2,AIANF1_2,NHOPIF1_2,TOMRF1_2
0,2014,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10881,7118,25224,1406699,170431,135342,110903,6999,5657,20823
1,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",NaN,...,85,24,50,3327,175,743,142,27,13,37
2,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",111.0,...,NaN,NaN,25,NaN,NaN,NaN,98,NaN,NaN,19
3,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",112.0,...,39,NaN,7,NaN,92,104,17,9,NaN,7
4,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",113.0,...,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561366,2023,United States,West,Pacific,Washington,"Yakima, WA",Yakima,62.0,Health Care and Social Assistance,621.0,...,NaN,NaN,NaN,NaN,NaN,66,NaN,NaN,NaN,NaN
561367,2023,United States,West,Pacific,Washington,"Yakima, WA",Yakima,62.0,Health Care and Social Assistance,623.0,...,NaN,NaN,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN
561368,2023,United States,West,Pacific,Washington,"Yakima, WA",Yakima,72.0,Accommodation and Food Services,NaN,...,NaN,NaN,NaN,NaN,NaN,51,NaN,NaN,NaN,NaN
561369,2023,United States,West,Pacific,Washington,"Yakima, WA",Yakima,81.0,Other Services (except Public Administration),NaN,...,NaN,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN
561370,2023,United States,West,Pacific,Washington,"Yakima, WA",Yakima,81.0,Other Services (except Public Administration),813.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#I need to change all of my columns after 'Establishments' to numeric
#df.iloc[:, 11:] = pd.to_numeric(df.iloc[:, 11:], errors= 'coerce')
#df.dtypes
#df.info()

In [10]:
#The above cell didn't work. After researching, I'm trying this code instead
#df.iloc[:, 11:] = df.iloc[:, 11:].apply(pd.to_numeric, errors='coerce')
#df.dtypes
#df.info()

In [11]:
#previous code still did not work. Trying this AI corrected version instead. 
# 1. Grab the first 11 columns (leave them exactly as they are)
left_side = df.iloc[:, :11]

# 2. Grab column 11 onwards and convert them to numbers
right_side = df.iloc[:, 11:].apply(pd.to_numeric, errors='coerce')

# 3. Glue them back together side-by-side (axis=1) into a new dataframe
df = pd.concat([left_side, right_side], axis=1)

df.dtypes
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 561371 entries, 0 to 561370
Columns: 276 entries, YEAR to TOMRF1_2
dtypes: float64(265), int64(3), str(8)
memory usage: 1.2 GB

In [12]:
# 0. Set the Industry Baseline filter (Keep 2-digit NAICS, drop 3-digit sub-sectors)
industry_filter = df['NAICS2'].notna() & df['NAICS3'].isna()

# 1. Isolate the purely National totals (Every geographical subdivision must be blank)
df_national_baselines = df[
    industry_filter &
    df['REGION'].isna() &
    df['DIVISION'].isna() &
    df['STATE'].isna() &
    df['CBSA'].isna() &
    df['COUNTY'].isna()
].copy()

# 2. Isolate the purely State-level totals (Has State, but no deeper geography)
df_state_totals = df[
    industry_filter &
    df['STATE'].notna() &
    df['COUNTY'].isna() &
    df['CBSA'].isna()
].copy()

# 3. Create your main granular dataset for Counties (Has County, but no CBSA overlap)
df_county_totals = df[
    industry_filter &
    df['COUNTY'].notna() &
    df['CBSA'].isna()
].copy()

# 4. Create your main granular dataset for CBSAs (Has CBSA, but no County overlap)
df_CBSA_total = df[
    industry_filter &
    df['CBSA'].notna() &
    df['COUNTY'].isna()
].copy()

In [13]:
#d = dtale.show(df_national_baselines)
#d.open_browser()
#df.info()

In [14]:
#d = dtale.show(df_state_totals)
#d.open_browser()
#df.info()

In [15]:
#d = dtale.show(df_county_totals)
#d.open_browser()
#df.info()

In [16]:
#d = dtale.show(df_CBSA_total)
#d.open_browser()
#df.info()

In [17]:
Computer_Folder = r'C:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC1_Cleaned_Master\'EEOC_Cleaned_Master_Stacked.csv'
df.to_csv(Computer_Folder, index=False)

In [18]:
import os

In [19]:
#Isolate the Total Value Categrories by Year
df_demographic_totals = df[df.iloc[:, 2:10].isna().all(axis=1)].copy()

In [20]:
#New code
def add_percentage_columns(df):
    """
    Takes a dataframe, finds all columns after TOTAL10, 
    calculates their percentage of TOTAL10, and appends them with a '_Pct' suffix.
    """
    # Safety check to ensure the column exists
    if 'TOTAL10' not in df.columns:
        return df
        
    # 1. Find the index of the 'TOTAL10' column 
    start_idx = df.columns.get_loc('TOTAL10') + 1
    
    # 2. Get the list of all demographic columns
    demographic_cols = df.columns[start_idx:]
    
    # 3. Divide all of those columns by TOTAL10 and multiply by 100
    df_pct = df[demographic_cols].div(df['TOTAL10'], axis=0) * 100
    
    # 4. Rename the new columns
    df_pct.columns = [f"{col}_Pct" for col in demographic_cols]
    
    # 5. Glue the new percentage columns onto the right side
    return pd.concat([df, df_pct], axis=1)

# Apply the function to the main master dataframe and all your filtered subsets
df = add_percentage_columns(df)
df_national_baselines = add_percentage_columns(df_national_baselines)
df_state_totals = add_percentage_columns(df_state_totals)
df_county_totals = add_percentage_columns(df_county_totals)
df_CBSA_total = add_percentage_columns(df_CBSA_total)
df_demographic_totals = add_percentage_columns(df_demographic_totals)

print("Percentage columns successfully added to all dataframes!")

Percentage columns successfully added to all dataframes!

In [22]:
#Saved all of my New Data Frames to CSV
folder_path = r'C:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC1_Cleaned_Master_v3.0'

master_file = os.path.join(folder_path, 'Master.csv')
national_file = os.path.join(folder_path, 'EEOC1_National_Baselines.csv')
state_file = os.path.join(folder_path, 'EEOC1_State_Totals.csv')
county_file = os.path.join(folder_path, 'EEOC1_County_Totals.csv')
cbsa_file = os.path.join(folder_path, 'EEOC1_CBSA_Total.csv')
demogr_file = os.path.join(folder_path, 'EEOC1_Demogr_Total.csv')

df.to_csv(master_file, index=False)
df_national_baselines.to_csv(national_file, index=False)
df_state_totals.to_csv(state_file, index=False)
df_county_totals.to_csv(county_file, index_label=False)
df_CBSA_total.to_csv(cbsa_file, index=False)
df_demographic_totals.to_csv(demogr_file, index=False)